version: '3'

services:
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    container_name: antlia-api
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    ports:
      - 8080:3000
    restart: always