version: '3'

services:
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    container_name: antlia-api
    environment:
      DATABASE_URL: "file:./dev.db"
    ports:
      - 3000:3000
    restart: on-failure