version: '3'

services:
  app:
    build: .
    container_name: micro-antlia-app-typescript
    restart: on-failure
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    networks:
      - mysql
    depends_on:
      - mysql

  mysql:
      image: mysql:8.0.28
      container_name: db_mysql_antlia
      environment:
        LANG : C.UTF-8
        MYSQL_USER: antlia
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: antlia
        TZ: UTC
      ports:
        - "3306:3306"
      volumes:
        - antlia-mysql:/var/lib/mysql
      networks:
        - mysql

volumes:
  antlia-mysql:

networks:
  mysql: